from bs4 import BeautifulSoup

# Step 1: Read the HTML file
with open("test-report-060325.html", "r", encoding="utf-8") as file:
    soup = BeautifulSoup(file, "html.parser")

# Step 2: Remove elements by class
for tag in soup.find_all("div", class_="title"):
    tag.decompose()

for tag in soup.find_all("a", class_="PREVNEXT"):
    tag.decompose()

# Find all <span> elements with class "TEXT"
for tag in soup.find_all("span", class_="TEXT"):
    if "Report generated by Burp Suite" in tag.get_text():
        tag.decompose()  # Remove only the matching span

# Step 3: Save the modified HTML file
with open("test-report-updated.html", "w", encoding="utf-8") as file:
    file.write(str(soup))

print("Unwanted elements removed! Check 'updated_report.html'.")
