# VERSION 1.9
from bs4 import BeautifulSoup

# Step 1: Read the existing report HTML file
with open("test-report-060325.html", "r", encoding="utf-8") as file:
    soup = BeautifulSoup(file, "html.parser")

# ---------------- Add Front Page ----------------

# Define the front page HTML content
front_page_html = """
<div id="front-page" style="width: 150mm; height: 230mm; margin: auto; padding: 50px; 
    font-family: Arial; text-align: center; border: 2px solid black; box-shadow: 5px 5px 15px rgba(0,0,0,0.2); 
    display: flex; flex-direction: column; justify-content: center; align-items: center;">
    
    <h1>Security Report</h1>
    <h2>Generated by Burp Suite</h2>
    <p><strong>Date:</strong> <span id="report-date"></span></p>
    <p><img src="logo.png" alt="Company Logo" width="200"></p>
    <hr style="width: 80%; border: 1px solid black;">
    
    <script>
        document.getElementById("report-date").innerText = new Date().toDateString();
    </script>
</div>
<br>

"""

# Parse the front page content as HTML
front_page_soup = BeautifulSoup(front_page_html, "html.parser")

# Insert the parsed front page at the beginning of <body>
soup.body.insert(0, front_page_soup)

# ---------------- Modify CSS ----------------

# Locate the <style> tag in the <head> section
style_tag = soup.find("style")

if style_tag and style_tag.string:
    # Modify the 'body' rule: update padding
    updated_css = []
    css_rules = style_tag.string.split("}")

    for rule in css_rules:
        if "body {" in rule:
            rule = rule.replace("padding: 0 15px", "padding: 0 80px")

        if "#container {" in rule:  # Optional: Modify container padding if needed
            rule = rule.replace("padding: 0 15px", "padding: 0 80px")

        if ".rr_div" in rule:  # Remove max-height from .rr_div
            rule = ";".join([prop for prop in rule.split(";") if "max-height" not in prop])

        updated_css.append(rule.strip())

    # Reconstruct the modified CSS
    style_tag.string = "}".join(updated_css) + "}"

# ---------------- Justify Text Inside <span class="TEXT"> ----------------

for span in soup.find_all("span", class_="TEXT"):
    if "style" in span.attrs:
        span["style"] += "; text-align: justify;"  # Append justify style
    else:
        span["style"] = "text-align: justify;"  # Add justify style

# ---------------- Remove Unwanted Elements ----------------

# Remove <div class="title">
for tag in soup.find_all("div", class_="title"):
    tag.decompose()

# Remove <a class="PREVNEXT">
for tag in soup.find_all("a", class_="PREVNEXT"):
    tag.decompose()

# Remove specific <span class="TEXT"> that contains "Report generated by Burp Suite"
for tag in soup.find_all("span", class_="TEXT"):
    if "Report generated by Burp Suite" in tag.get_text():
        tag.decompose()

# ---------------- Save the Modified HTML File ----------------

with open("test-report-updated.html", "w", encoding="utf-8") as file:
    file.write(str(soup))

print("Front page added, CSS updated, text justified, and elements removed! Check 'test-report-updated.html'.")
