#VERSION 1.5
from bs4 import BeautifulSoup

# Step 1: Read the existing report HTML file
with open("test-report-060325.html", "r", encoding="utf-8") as file:
    soup = BeautifulSoup(file, "html.parser")

# Step 2: Define the front page HTML content
front_page_html = """
<div id="front-page" style="text-align:center; padding:50px; font-family:Arial;">
    <h1>Security Report</h1>
    <h2>Generated by Burp Suite</h2>
    <p><strong>Date:</strong> <span id="report-date"></span></p>
    <p><img src="logo.png" alt="Company Logo" width="200"></p>
    
    <hr>
    <script>
        document.getElementById("report-date").innerText = new Date().toDateString();
    </script>
</div>
"""

# Step 3: Parse the front page content as HTML
front_page_soup = BeautifulSoup(front_page_html, "html.parser")

# Step 4: Insert the parsed HTML at the beginning of <body>
soup.body.insert(0, front_page_soup)

#----------------
# Remove elements by class
for tag in soup.find_all("div", class_="title"):
    tag.decompose()

for tag in soup.find_all("a", class_="PREVNEXT"):
    tag.decompose()

# Find all <span> elements with class "TEXT"
for tag in soup.find_all("span", class_="TEXT"):
    if "Report generated by Burp Suite" in tag.get_text():
        tag.decompose()  # Remove only the matching span

#----------------

# Step 4: Save the modified HTML file
with open("test-report-updated.html", "w", encoding="utf-8") as file:
    file.write(str(soup))

print("Front-page div added at the beginning! Check 'test-report-updated.html'.")
